### ISSUE TITLE
Wrong encoding when editing profiles titles 

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/data-quality-filter-service#3] opened 2022-03-04 10:50 UTC
Editing utf-8 titles:

![image](https://user-images.githubusercontent.com/180085/156750791-57cbb37c-7576-4acf-a5d4-5fb1c6caffe4.png)

cause wrong charsets:

![image](https://user-images.githubusercontent.com/180085/156749314-0f4ede12-8824-4d18-b1ac-b9e7019aa06d.png)

The database created by `ala-install` is `UTF-8` and also, if the profile is imported, does not have encoding issues. So it sounds like is specific to this form.

I tried to setup the datasource url with `useUnicode=true&characterEncoding=UTF-8` but didn't solve it.

**Comment by adam-collins** [comment] 2024-01-19 02:11
An example string please. 

I did find an example that reproduced the error, but I lost it and cannot find another that fails.

**Comment by adam-collins** [comment] 2024-03-27 00:49
Feel free to reopen with an example.

**Comment by vjrj** [comment] 2024-03-29 11:28
With `áéíóú` or `äëïöü` for instance in the `Description` using `1.4.0`, that is any non-latin character.

![image](https://github.com/AtlasOfLivingAustralia/data-quality-filter-service/assets/180085/fe879c79-2df8-4b82-abc2-a40eade08759)

![image](https://github.com/AtlasOfLivingAustralia/data-quality-filter-service/assets/180085/be898471-f79b-47d5-bfc7-f085280f61c0)

In the DB:
```
data-quality=# select * from public.quality_profile;
 id | version | display_order | short_name |      date_created       | contact_name  |      last_updated       |  name   | is_default | contact_email | enabled |   description   
----+---------+---------------+------------+-------------------------+---------------+-------------------------+---------+------------+---------------+---------+-----------------
  1 |       1 |             1 | default    | 2024-03-29 10:35:54.787 | Support Email | 2024-03-29 11:21:28.558 | Default | t          |               | t       | �����
(1 row)
```

```
data-quality=# SHOW SERVER_ENCODING;
 server_encoding 
-----------------
 SQL_ASCII
(1 row)
```
Compared with the spatial layersdb: 
```
layersdb=# SHOW SERVER_ENCODING;
 server_encoding 
-----------------
 UTF8
(1 row)
```

**Comment by adam-collins** [comment] 2024-04-17 00:13
I cannot reproduce.

A fresh install of data-quality-filter-service using ala-install creates a database with server encoding UTF-8. Not sure how you get SQL_ASCII.

Is it a problem only on older installations?

**Comment by adam-collins** [comment] 2024-05-02 23:09
Given that it is a database creation issue (wrong server encoding), I'll close this.

**Closed as completed by adam-collins** 2024-05-02 23:09 UTC
